name: Build-My-Deb
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Theos
        uses: theos/setup-theos@master
      - name: Build
        run: make FINALPACKAGE=1
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: My-New-Hack
          path: packages/*.deb
